FROM openjdk:11-jre-slim
WORKDIR /usr/src
ENV MONGO_URI mongodb://localhost:27017/Test
ADD ./target/soulmateservice-0.0.1-SNAPSHOT.jar /usr/src/soulmateservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","restful-0.0.1-SNAPSHOT.jar"]