version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongoconnection
restful:
  image: pajayvarmap/soultmate:latest
  container_name: restfulservice
  ports:
    - 8080:8085
  environment:
    MONGO_URI: mongodb://mongodb:27017/Test
  depends_on:
    - mongodb
  restart: always